/**********************************************************************
File Name : t_sp_dm_pt1
Created/Modified by : Jasvinder Bagdi / jb668127
Created/Modified Date : 10-MAY-2022
Driver version : 17
Change History : (Note: The time is captured in GMT/BST time zone) 
1 12-NOV-2021 15:33:01 jb668127 Initial Driver Creation 
2 12-NOV-2021 16:03:06 jb668127 Parameter update 
3 12-NOV-2021 16:04:26 jb668127 Parameter update 
4 12-NOV-2021 16:23:02 jb668127 Parameter update 
5 17-NOV-2021 09:13:12 jb668127 Parameter update 
6 17-NOV-2021 09:16:45 jb668127 Parameter update 
7 17-NOV-2021 09:23:55 jb668127 Parameter update 
8 17-NOV-2021 09:49:21 jb668127 Parameter update 
9 17-NOV-2021 09:50:01 jb668127 Parameter update 
10 01-DEC-2021 12:18:24 jb668127 Parameter update 
11 07-DEC-2021 10:33:29 jb668127 Parameter update 
12 07-DEC-2021 10:39:35 jb668127 Parameter update 
13 08-DEC-2021 15:40:45 jb668127 Parameter update 
14 08-DEC-2021 15:43:46 jb668127 Parameter update 
15 09-DEC-2021 09:09:59 jb668127 Parameter update 
16 31-JAN-2022 11:08:17 vb223914 Bulk Parameter update 
17 25-FEB-2022 14:39:31 jb668127 Parameter update 
**********************************************************************/
options sasautos=('/arenv/arprod/gsk4182136/mid215199/iss_01/code' '/local1/apps/SAS/9.4/SASFoundation/9.4/sasautos');
%ts_setup(
	d_centid=,
	d_datadate=,
	d_foot1=%nrstr([1] x Age is imputed from year of birth. The calculation uses 30 June as the day and month and calculates),
	d_foot2=%nrstr(age relative to Screening date.),
	d_foot3=%nrstr(Note: Percentages are calculated from the displayed n counts.),
	d_foot4=,
	d_foot5=,
	d_foot6=,
	d_foot7=,
	d_foot8=,
	d_foot9=,
	d_keeppopvars=,
	d_language=,
	d_pop=SAFFL,
	d_popdata=,
	d_poplbl=Safety,
	d_ptrtfmt=,
	d_rtfyn=Y,
	d_stype=,
	d_subjid=,
	d_subpop=,
	d_subset=,
	d_trt_inper=,
	d_trtdata=,
	d_trtfmt=,
	d_trtvar=,
	r_stype=PG,
	r_subjid=USUBJID,
	r_centid=SITEID,
	r_trtvar=A,
	r_study_id=mid215199,
	r_study_desc=,
	r_indic=Virus Diseases,
	r_ardata=/arenv/arprod/gsk4182136/mid215199/iss_01/ardata,
	r_sdtmdata=/arenv/arprod/gsk4182136/mid215199/iss_01/sdtm,
	r_adamdata=/arenv/arprod/gsk4182136/mid215199/iss_01/adamdata,
	r_dddata=/arenv/arprod/gsk4182136/mid215199/iss_01/dddata,
	r_rawdata=/arenv/arprod/gsk4182136/mid215199/iss_01/rawdata,
	r_dmdata=/arenv/arprod/gsk4182136/mid215199/iss_01/dmdata,
	r_pkdata=/arenv/arprod/gsk4182136/mid215199/iss_01/pkdata,
	r_usage=DD,
	r_refdata=/arenv/artools/sas/macros,
	r_macdirs='.' '/arenv/arprod/gsk4182136/mid215199/iss_01/code',
	r_rlblfile=,
	r_slblfile=,
	r_clblfile=,
	r_trt_inper=N,
	r_pop=SAFFL,
	r_diction=/arenv/arprod/gsk4182136/mid215199/iss_01/refdata,
	r_trtfmt=rt_trtf.,
	r_ptrtfmt=rt_ptrtf.,
	r_datadate=,
	r_language=BRENG,
	r_popdata=adamdata.adsl,
	r_gfmtdir=/local1/apps/central_customs/dictionaries,
	r_trtdata=adamdata.adsl,
	r_keeppopvars=_NONE_,
	r_datatype=CDISC,
	d_pgmpth=/arenv/arprod/gsk4182136/mid215199/iss_01/drivers/t_sp_dm_pt1.sas,
	r_rfmtdir=/arenv/arprod/gsk4182136/mid215199/iss_01/refdata,
	r_sfmtdir=/arenv/arprod/gsk4182136/mid215199/refdata,
	r_cfmtdir=/arenv/arprod/gsk4182136/refdata,
	d_dsplytyp=T,
	d_dsplynum=1.09,
	d_outfile=/arenv/arprod/gsk4182136/mid215199/iss_01/output/t_sp_dm_pt1,
	d_title1=%nrstr(Summary of Demographic Characteristics),
	d_title2=%nrstr(by Placebo vs Sotrovimab),
	d_title3=,
	d_title4=,
	d_title5=,
	d_title6=,
	d_title7=,
	d_fontsize=L10,
	d_status=I,
	d_userid=kr742939,
	d_analy_disp=A,
	d_debug=0);
%rd_dm1c(
	trtvar=tr01ag1,
	subgroup_txt=,
segment1=%str(groupByVarsNumer=trtn trt (Sex1='n') sexn sex1,dsetout=segment1_out(rename=(sex1=tt_decode1 sexn=tt_code1)),codedecodevarpairs=trtn trt sexn sex1,
postsubset=%str(if 1;if sex1='F' then sex1='Female'; else if sex1='M' then sex1='Male';drop tt_grplabel;temp='Sex';rename temp=tt_grplabel;)),
	segment2=%str(analysisVars=aage,postsubset=if 1;drop tt_grplabel;temp='Age (YEARS) [1]';rename temp=tt_grplabel;),
segment3=%str(groupByVarsNumer=trtn trt (agegr1='n') agegr1n agegr1,dsetout=segment3_out(rename=(agegr1=tt_decode1 agegr1n=tt_code1)),codedecodevarpairs=trtn trt agegr1n agegr1, psformat=/*agegr1n agegr1n.*/,
postsubset=if 1;drop tt_grplabel;temp='Age Group (YEARS) [1]';rename temp=tt_grplabel;),
segment4=%str(groupByVarsNumer=trtn trt (agegr2='n') agegr2n agegr2,dsetout=segment4_out(rename=(agegr2=tt_decode1 agegr2n=tt_code1)),codedecodevarpairs=trtn trt agegr2n agegr2, psformat=/*agegr2n agegr2n.*/,
postsubset=if 1;drop tt_grplabel;temp='Age Group 2 (YEARS) [1]';rename temp=tt_grplabel;),
segment5=%str(dsetinnumer=_dsetin(where=(ETHNICN ne .)), dsetindenom=_dsetin(where=(ETHNICN ne .)), groupByVarsNumer=trtn trt (ETHNIC='n') ETHNICN ETHNIC,dsetout=segment5_out(rename=(ETHNIC=tt_decode1 ETHNICN=tt_code1)),
codedecodevarpairs=trtn trt ETHNICN ETHNIC,psformat=ETHNICN ETHNICN.,postsubset=if 1;drop tt_grplabel;temp='Ethnicity';rename temp=tt_grplabel;),
segment6=%str(dsetinnumer=_dsetin(where=(race_ ne ' ')), dsetindenom=_dsetin(where=(race_ ne ' ')),groupByVarsNumer=trtn (racen_char='n') racen_char, groupbyvarsdenom=trtn,codedecodevarpairs= racen_char race_ trtn trt,psformat=racen_char $hlracen.,
totalforvar=trtn,GROUPBYVARPOP=trtn,DSETOUT=segment6_out(rename=(racen_char=tt_code1 race_=tt_decode1)), postsubset=%str(if 1; drop tt_grplabel;temp='High Level Race';rename temp=tt_grplabel;)),
segment7=%str(dsetinnumer=_dsetin(where=(arace ne ' ')), dsetindenom=_dsetin(where=(arace ne ' ')),groupByVarsNumer=trtn (arace='n') aracen arace, groupbyvarsdenom=trtn,codedecodevarpairs= aracen arace trtn trt,psformat=aracen racen.,totalforvar=trtn,
GROUPBYVARPOP=trtn,DSETOUT=segment7_out(rename=(aracen=tt_code1 arace=tt_decode1)), postsubset=%str(if 1; drop tt_grplabel;temp='Race Detail';rename temp=tt_grplabel;)),
	segment8=%str(analysisVars=heightbl,analysisvardps=0,statsdps=min +0 max +0 median +1 mean +1 std +2,postsubset=if 1;drop tt_grplabel;temp='Height (cm)';rename temp=tt_grplabel;),
	segment9=%str(analysisVars=weightbl,analysisvardps=1,statsdps=min +0 max +0 median +1 mean +1 std +2,postsubset=if 1;drop tt_grplabel;temp='Weight (kg)';rename temp=tt_grplabel;),
	segment10=%str(analysisVars=bmibl,analysisvardps=1,statsdps=min +0 max +0 median +1 mean +1 std +2,postsubset=if 1;drop tt_grplabel;temp='BMI (kg/m^2)';rename temp=tt_grplabel;),
	segment11=,
	segment12=,
	segment13=,
	segment14=,
	segment15=,
	segment16=,
	segment17=,
	segment18=,
	segment19=,
	segment20=,
	acrosscolvarprefix=tt_result,
	acrossvar=trtn,
	acrossvardecode=trt,
	acrossvarlistname=,
	addbignyn=Y,
	alignyn=Y,
	denormyn=Y,
	dsetin=adamdata.adsl,
	dsetout=,
	break1=,
	break2=,
	break3=,
	break4=,
	break5=,
	byvars=,
	centrevars=,
	colspacing=2,
	columns=tt_segorder tt_grplabel tt_code1  tt_decode1 tt_result000:  tt_result9999,
	computebeforepagelines=,
	computebeforepagevars=,
	dddatasetlabel=DD dataset for td_dm1 display,
	defaultwidths=,
	descending=,
	display=Y,
	flowvars=_ALL_,
	formats=,
	idvars=tt_segorder  tt_grplabel tt_code1 tt_decode1,
	labels=,
	labelvarsyn=Y,
	leftvars=,
	linevars=,
	noprintvars=tt_segorder tt_code1,
	nowidowvar=tt_segorder,
	orderdata=,
	orderformatted=,
	orderfreq=,
	ordervars=tt_segorder  tt_grplabel tt_code1,
	overallsummary=N,
	pagevars=,
	proptions=headline,
	rightvars=,
	sharecolvars=tt_grplabel   tt_decode1,
	sharecolvarsindent=2,
	skipvars=tt_segorder,
	splitchar=~,
	stackvar1=,
	stackvar2=,
	stackvar3=,
	stackvar4=,
	stackvar5=,
	stackvar6=,
	stackvar7=,
	stackvar8=,
	stackvar9=,
	stackvar10=,
	stackvar11=,
	stackvar12=,
	stackvar13=,
	stackvar14=,
	stackvar15=,
	varlabelstyle=SHORT,
	varspacing=,
	varstodenorm=tt_result,
	widths=tt_grplabel 50  tt_decode1 50 tt_result: 15,
	xmldefaults=&g_rfmtdir/dm1_defaults_a.xml,
	ynvars=,
	ynorderfmt=$ynorder.,
	yndecodefmt=$yndecod.,
	trtcdvar=,
	trtgrpvar=,
postsubset=if tt_segorder=3 and compress(tt_code1)in( '99') then delete;if tt_code1="n" then do;tt_decode1=tt_code1; tt_code1="";end;if tt_segorder=10 and tt_decode1="n" then tt_code1=1;tt_code1=strip(tt_code1);tt_code1=input(tt_code1,
best8.);if compress(tt_decode1)='n' and tt_result0001='' then tt_result0001='  0';if tt_grplabel='Race Detail' and missing(tt_decode1) then do;tt_decode1='OTHER';tt_code1='99';end;,
	presubset=sexn=2-sexn);
