/**********************************************************************
File Name : t_dm

**********************************************************************/

%demo(
	trtvar=tr01ag1,
	subgroup_txt=,
segment1=%str(groupByVarsNumer=trtn trt (Sex1='n') sexn sex1,dsetout=segment1_out(rename=(sex1=tt_decode1 sexn=tt_code1)),codedecodevarpairs=trtn trt sexn sex1,
postsubset=%str(if 1;if sex1='F' then sex1='Female'; else if sex1='M' then sex1='Male';drop tt_grplabel;temp='Sex';rename temp=tt_grplabel;)),
	segment2=%str(analysisVars=aage,postsubset=if 1;drop tt_grplabel;temp='Age (YEARS) [1]';rename temp=tt_grplabel;),
segment3=%str(groupByVarsNumer=trtn trt (agegr1='n') agegr1n agegr1,dsetout=segment3_out(rename=(agegr1=tt_decode1 agegr1n=tt_code1)),codedecodevarpairs=trtn trt agegr1n agegr1, psformat=/*agegr1n agegr1n.*/,
postsubset=if 1;drop tt_grplabel;temp='Age Group (YEARS) [1]';rename temp=tt_grplabel;),
segment4=%str(groupByVarsNumer=trtn trt (agegr2='n') agegr2n agegr2,dsetout=segment4_out(rename=(agegr2=tt_decode1 agegr2n=tt_code1)),codedecodevarpairs=trtn trt agegr2n agegr2, psformat=/*agegr2n agegr2n.*/,
postsubset=if 1;drop tt_grplabel;temp='Age Group 2 (YEARS) [1]';rename temp=tt_grplabel;),
segment5=%str(dsetinnumer=_dsetin(where=(ETHNICN ne .)), dsetindenom=_dsetin(where=(ETHNICN ne .)), groupByVarsNumer=trtn trt (ETHNIC='n') ETHNICN ETHNIC,dsetout=segment5_out(rename=(ETHNIC=tt_decode1 ETHNICN=tt_code1)),
codedecodevarpairs=trtn trt ETHNICN ETHNIC,psformat=ETHNICN ETHNICN.,postsubset=if 1;drop tt_grplabel;temp='Ethnicity';rename temp=tt_grplabel;),
segment6=%str(dsetinnumer=_dsetin(where=(race_ ne ' ')), dsetindenom=_dsetin(where=(race_ ne ' ')),groupByVarsNumer=trtn (racen_char='n') racen_char, groupbyvarsdenom=trtn,codedecodevarpairs= racen_char race_ trtn trt,psformat=racen_char $hlracen.,
totalforvar=trtn,GROUPBYVARPOP=trtn,DSETOUT=segment6_out(rename=(racen_char=tt_code1 race_=tt_decode1)), postsubset=%str(if 1; drop tt_grplabel;temp='High Level Race';rename temp=tt_grplabel;)),
segment7=%str(dsetinnumer=_dsetin(where=(arace ne ' ')), dsetindenom=_dsetin(where=(arace ne ' ')),groupByVarsNumer=trtn (arace='n') aracen arace, groupbyvarsdenom=trtn,codedecodevarpairs= aracen arace trtn trt,psformat=aracen racen.,totalforvar=trtn,
GROUPBYVARPOP=trtn,DSETOUT=segment7_out(rename=(aracen=tt_code1 arace=tt_decode1)), postsubset=%str(if 1; drop tt_grplabel;temp='Race Detail';rename temp=tt_grplabel;)),
	segment8=%str(analysisVars=heightbl,analysisvardps=0,statsdps=min +0 max +0 median +1 mean +1 std +2,postsubset=if 1;drop tt_grplabel;temp='Height (cm)';rename temp=tt_grplabel;),
	segment9=%str(analysisVars=weightbl,analysisvardps=1,statsdps=min +0 max +0 median +1 mean +1 std +2,postsubset=if 1;drop tt_grplabel;temp='Weight (kg)';rename temp=tt_grplabel;),
	segment10=%str(analysisVars=bmibl,analysisvardps=1,statsdps=min +0 max +0 median +1 mean +1 std +2,postsubset=if 1;drop tt_grplabel;temp='BMI (kg/m^2)';rename temp=tt_grplabel;),
	segment11=,
	segment12=,
	segment13=,
	segment14=,
	segment15=,
	segment16=,
	segment17=,
	segment18=,
	segment19=,
	segment20=,
	acrosscolvarprefix=tt_result,
	acrossvar=trtn,
	acrossvardecode=trt,
	acrossvarlistname=,
	addbignyn=Y,
	alignyn=Y,
	denormyn=Y,
	dsetin=adamdata.adsl,
	dsetout=,
	break1=,
	break2=,
	break3=,
	break4=,
	break5=,
	byvars=,
	centrevars=,
	colspacing=2,
	columns=tt_segorder tt_grplabel tt_code1  tt_decode1 tt_result000:  tt_result9999,
	computebeforepagelines=,
	computebeforepagevars=,
	dddatasetlabel=DD dataset for td_dm1 display,
	defaultwidths=,
	descending=,
	display=Y,
	flowvars=_ALL_,
	formats=,
	idvars=tt_segorder  tt_grplabel tt_code1 tt_decode1,
	labels=,
	labelvarsyn=Y,
	leftvars=,
	linevars=,
	noprintvars=tt_segorder tt_code1,
	nowidowvar=tt_segorder,
	orderdata=,
	orderformatted=,
	orderfreq=,
	ordervars=tt_segorder  tt_grplabel tt_code1,
	overallsummary=N,
	pagevars=,
	proptions=headline,
	rightvars=,
	sharecolvars=tt_grplabel   tt_decode1,
	sharecolvarsindent=2,
	skipvars=tt_segorder,
	splitchar=~,
	stackvar1=,
	stackvar2=,
	stackvar3=,
	stackvar4=,
	stackvar5=,
	stackvar6=,
	stackvar7=,
	stackvar8=,
	stackvar9=,
	stackvar10=,
	stackvar11=,
	stackvar12=,
	stackvar13=,
	stackvar14=,
	stackvar15=,
	varlabelstyle=SHORT,
	varspacing=,
	varstodenorm=tt_result,
	widths=tt_grplabel 50  tt_decode1 50 tt_result: 15,
	xmldefaults=&g_rfmtdir/dm1_defaults_a.xml,
	ynvars=,
	ynorderfmt=$ynorder.,
	yndecodefmt=$yndecod.,
	trtcdvar=,
	trtgrpvar=,
postsubset=if tt_segorder=3 and compress(tt_code1)in( '99') then delete;if tt_code1="n" then do;tt_decode1=tt_code1; tt_code1="";end;if tt_segorder=10 and tt_decode1="n" then tt_code1=1;tt_code1=strip(tt_code1);tt_code1=input(tt_code1,
best8.);if compress(tt_decode1)='n' and tt_result0001='' then tt_result0001='  0';if tt_grplabel='Race Detail' and missing(tt_decode1) then do;tt_decode1='OTHER';tt_code1='99';end;,
	presubset=sexn=2-sexn);
